language: node_js
node_js:
  - "0.10"
branches:
  only:
    - master
script: "npm run-script test-ci"
after_script: "npm install coveralls@2.10.0 && cat ./test/coverage/lcov.info | coveralls"
